### ISSUE TITLE
Adding AC Inverter Off / On / Standby possible?

### ISSUE THREAD

**Issue by Christyria** [taHC81/MUST-ESPhome#1]
Hello,

and thank you for your great Project.
The ESP Software runs here flawlessy on my PV1800 12V 1kW System - but i have an important "Feature Request":

Is it possible (With the correct MODBus Register) to switch the internal AC Inverter On Off and in Stand By Mode? (Stand By Mode= AC is in Power Efficient Mode, it checks every 6 seconds if there is an Load higher than 25 Watts and automatically shuts on the AC Inverting full on, when the Load disappear it goes to Energy Saving)

Because the PV1800 runs on old PB Batterys and i need the switable AC over the ESP Software to turn the AC off, on or in Stand By Mode to save PB Battery Power. The Power Draw in Full on is at about 1,65A and the Power Draw is all 6 Seconds 1A then off.

Many Thanks.

**Comment by taHC81** [comment]
Hello, it looks like a register:

20104 |Inverter search mode enable | 0：OFF 1：ON

0: If disabled, no matter connect load is low or high, the on/off status of inverter output will not be effected.                                       

1: If enable, the inverter begins search mode if the AC load connected is pretty low or not detected. The inverter’s “search” mode reduces stand-by energy consumption during no-load conditions.

If so, then please try to add following code into "switch:" section below. It's just a try, I'm not going to test it on my production plant.

```
switch:
  - platform: modbus_controller
    modbus_controller_id: must
    id: inverter_search_mode
    name: "Inverter search mode"
    address: 20104
    value_type: U_WORD
```
