### ISSUE TITLE
accumulated_charger_power sensor does not show data

### ISSUE THREAD

**Issue by ctanapik** [taHC81/MUST-ESPhome#7]
Hi! I faced an issue with MUST PV18-3224 VPM.
The Accumulated charger power sensor does not provide data of the energy given on the battery

I have this sensor in the ESP config: 
```
   - platform: modbus_controller
    address: 15217
    register_type: holding
    name: "Accumulated charger power MWh"
    id: charger_total_mwh
    internal: true
    unit_of_measurement: "MWh"
    accuracy_decimals: 1

  - platform: modbus_controller
    address: 15218
    register_type: holding
    name: "Accumulated charger power kWh"
    id: charger_total_kwh
    internal: true
    unit_of_measurement: "kWh"
    accuracy_decimals: 1
    filters:
      multiply: 0.1

  - platform: template
    name: "Accumulated charger power"
    unit_of_measurement: "kWh"
    device_class: "energy"
    state_class: "total_increasing"
    lambda: |-
     return (id(charger_total_mwh).state * 1000.0 + id(charger_total_kwh).state );
    accuracy_decimals: 1
```

<img width="598" alt="Знімок екрана 2024-09-24 о 10 40 42" src="https://github.com/user-attachments/assets/e005394a-6b2e-4a71-83de-37ba28d283b3">

Only once, at the begining, it was set to 0,7 kWh and stays with that value no matter how much I keep charging the battery
At the same time, Accumulated discharger power sensor shows me correct data of discharging the battery

Maybe someone has similar issue and can help me fixing it?
